### ISSUE TITLE
how to set dns server

### ISSUE THREAD

**Issue by wildsky95** [jasoncoon/esp8266-fastled-webserver#113]
his jason , thanks for great job ! 
i want to have sth like dns server on my esp 
for example 
i wanna type http://wildsky in webpage to access the webserver instead of http://192.168.4.1
how could i do it ???

**Comment by jasoncoon** [comment]
You can use mDNS: https://tttapa.github.io/ESP8266/Chap08%20-%20mDNS.html

There's already code in this project for it, but I've commented it out since I don't use it: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L31

Just search for mDNS and uncomment those lines.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
