### ISSUE TITLE
Fire Effect locks up with matrix

### ISSUE THREAD

**Issue by timbudtwo** [jasoncoon/esp8266-fastled-webserver#116]
Whenever I choose any of the bottom patterns, for example Fire, it locks up the arduino and requires reprogramming because the spliffs retain the last pattern and it cannot restart.

**Comment by jasoncoon** [comment]
You can disable loading settings from EEPROM until this issue is resolved by commenting out this line: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L235

Are you using the latest version of the code?  There used to be bugs in several patterns with > 256 LEDs.

**Comment by timbudtwo** [comment]
Jason,
Yeah, I built it from the copy I downloaded late January. Looks like the most recent change was made december?

**Comment by jasoncoon** [comment]
Looks like it was fixed on Nov 7: https://github.com/jasoncoon/esp8266-fastled-webserver/commit/e2d546bf8cf344226fa5888a392dd653013944ad
