### ISSUE TITLE
Sync Patterns Across Multiple Devices

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-webserver#117]
I have identical data files and code uploaded to 3 esp8266. IP Addresses 32, 33, and 34.

When I quickly switch them all to Pride, for instance. They don't start at the beginning of pride.

Is it possible to put them all on 32 for instance?

 would that sync up the patterns?

**Comment by mattncsu** [comment]
Maybe you could run NTP on the ESPs and tell them to run the pattern at a specific time. If the ESPs are close to each other, you could connect the data lines and you always want them to show the same thing, you could connect the data lines in parallel and run them off a single ESP.

**Comment by tobi01001** [comment]
You cannot put all on the same IP-address.... That will not work in your network.

You could modify the web-app (index.htm / application.js) to send the HTTP GET to every esp. This could also be done with the Websocketserver - may be a bit faster.

However, it still depends on how synchonized you would like them to have / to be? 
If they are always in sync then a parallel data line is more easy than digging in the code.

To sync the patterns you not only need to start them at the same time but also to sync their parameters like resetting the static variables to a initial value on the first call of the function and maybe providing the beatsin88 functions with a timebase...

Then it depends also on the type of leds, number of leds. If you call the esp in the middle (or even worse) beginning of writing the data to a 300 leds strip, the new pattern will wait 9 ms before being activated. So you could still have 9+ ms out of sync (which may not be visible).

I have a home automation sever running on a raspberry pie (called fhem) and adopted a module to interact with the webserver on the esp. This way I can control all of my leds at once (there is way for improvement) but I don't care about syncing since all are in different rooms.

**Comment by mattncsu** [comment]
Depending on what you're trying to accomplish, you could also build a couple [ESPixelSticks](https://www.doityourselfchristmas.com/wiki/index.php/ESPixel_Stick_%26_ESPixel_Pops) for dirt cheap and coordinate all your lights with [Falcon FPP](https://falconchristmas.com/wiki/Falcon_FPP) running on a Pi or other small computer.  I ran a coordinated "show" with around 1000 pixels across 7 ESP-01 based ESPixelSticks over the holidays.

**Comment by atatistcheff** [comment]
I did it by using a shell script to call curl and send the pattern directly
to the various ESPs at the same time.  It's actually one after another but
I don't wait for the GET to complete before sending it to the next ESP so
it's virtually simultaneous.

https://gist.github.com/atatistcheff/7e49e9915f46b7ed28ddf3670283104b



Alex Tatistcheff
alext@pobox.com

traceroute bad.horse - do it now!

**Comment by jordanadania** [comment]
i have strips going around the ceiling of an Arcade Escape Room I work at. I wanna use pride setting, but i want them to phase into the single color mode at the same time. They have different power sources that are across the room from each other as well. aside from flipping a breaker... idk what to do.

**Comment by jordanadania** [comment]
To sync everything up I ended up using extension cords to run everything on one power supply.

However, I am very interested in switching to the parallel data line method so I can upgrade to a more favored pattern. Can anyone point me in a good direction to learn how to do that?

Thanks in advance!

**Comment by jordanadania** [comment]
I just changed the code and ran multiple data pins with common grounds.

  FastLED.addLeds<LED_TYPE, 6, COLOR_ORDER>(leds, NUM_LEDS);
  FastLED.addLeds<LED_TYPE, 7, COLOR_ORDER>(leds, NUM_LEDS);
