### ISSUE TITLE
Google assistant?

### ISSUE THREAD

**Issue by rRrepotec** [jasoncoon/esp8266-fastled-webserver#128]
How can I turn on/off with google assistant and ifttt?

**Comment by mc9625** [comment]
Is not that hard actually.

If you want to have total control of your device via voice commands, you can do it in two ways:

a) Easy to implement, but requires to expose your Arduino to internet opening a port on your router, for instance pointing the 80 to the IP of your Arduino and then use a DDNS service in order to use a domain name instead of a dynamic IP (unless your ISP does provide you a static IP). Then simply create an applet using Google Home and a Web Request like: URL = http://yourIP/power?value=0,    METHOD = PUT,  CONTENT TYPE = application/json 

b) Little bit difficult to implement, but it doesn't require to expose the Arduino and deal with router or DDNS service: You could implement an MQTT service, like ADAFRUIT for instance. It's not that hard to implement it, you can literally start from the Adafruit example. With an ESP8266 for instance is not that hard.

There are other methods of course, but the concept is: make your device reachable from internet and use a web request (easy but not safe) or make your device "wait for command" (in case of MQTT is more "look for command"). 

If you simply want to power it on/off via voice, you can even connect your device to a smart power plug and simply turn it on/off via Google Home, but in that case your are limited to power, if you really want to use your voice to interact with the device, the other two options are better.

Cheers

**Comment by jasoncoon** [comment]
Closing this issue, but feel free to reopen it if needed.
