### ISSUE TITLE
Getting "Not Found: /" (FIX)

### ISSUE THREAD

**Issue by mbd-shift** [jasoncoon/esp8266-fastled-webserver#184]
Used ESP8266FS 0.5.0

Fix: In esp8266-fastled-webserver.ino line 255 

Changed
 Dir dir = SPIFFS.openDir("/");
to 
 Dir dir = SPIFFS.openDir("");

**Comment by Quantum99k** [comment]
yeah that didn't work for me. I"m using the nodemcu 12E

**Comment by mbd-shift** [comment]
try

`"."`

**Comment by Ragebone** [comment]
both didn't work for me on a node mcu v3 lolin thingy.

**Comment by shadik42** [comment]
Do you uploaded webapp to SPIFFS?

https://github.com/jasoncoon/esp8266-fastled-webserver#installing

**Comment by henrygab** [comment]
With the switch to the use of LittleFS, you will have to re-upload the file system at least once, so it overwrites SPIFFS with LittleFS.

This is true even if you previously were using SPIFFS.

It's recommended to use PlatformIO (rather than Arduino) to create and upload the file system image, as the logging is better.  See https://github.com/jasoncoon/esp8266-fastled-webserver/discussions/207#discussioncomment-1655195 for how to start using PlatformIO.

Of course, Arduino still works.

If you are still getting this error, there are some possible reasons:
1. Flash writing failed because of low power.  This can happen if using an unpowered USB hub to power the ESP module, as writing to the flash takes more current.  Plug directly into the computer's USB port, or use a powered USB3 hub.
2. Flash writing failed because hardware failure.  Flash has limited write cycles.  It's just a possibility, but this is very hard to diagnose precisely.

I will close this issue due to age.  However, if you have this problem, please open a new issue with confirmation that you're using a powered USB hub (or direct-to-PC USB connection), whether you're using PlatformIO or Arduino for the upload, and any relevant logging output.
