### ISSUE TITLE
Not found: /

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-webserver#222]
I have been using your webapp for awhile, but recently started getting Not Found.

What's new?

**Comment by jasoncoon** [comment]
Hey Jordan, recently @henrygab pitched in to start consolidating all of the separate branches into one that's controlled via preprocessor directives, along with adding PlatformIO support (Arduino is still supported), and switching from SPIFFS (which is deprecated) to LittleFS.  He's documented the changes extremely well:

LittleFS: https://github.com/jasoncoon/esp8266-fastled-webserver/pull/209
PlatformIO: https://github.com/jasoncoon/esp8266-fastled-webserver/discussions/207#discussioncomment-1655195

Let us know if you still have any problems or questions.

**Comment by jordanadania** [comment]
I found success going back to pre-wifi manager.  Much more reliable for me.  Thanks for the info.  Grats on upgrading to something more complex.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Jason Coon ***@***.***> Date: 12/6/21  9:33 AM  (GMT-05:00) To: jasoncoon/esp8266-fastled-webserver ***@***.***> Cc: Jordan Adania ***@***.***>, Author ***@***.***> Subject: Re: [jasoncoon/esp8266-fastled-webserver] Not found: / (Issue #222) 
Hey Jordan, recently @henrygab pitched in to start consolidating all of the separate branches into one that's controlled via preprocessor directives, along with adding PlatformIO support (Arduino is still supported), and switching from SPIFFS (which is deprecated) to LittleFS.  He's documented the changes extremely well:
LittleFS: #209
PlatformIO: #207 (comment)
Let us know if you still have any problems or questions.

**Comment by henrygab** [comment]
@jordanadania 

To fix, you need to create and upload the LittleFS image.  This is normally a one-time cost per physical board, unless you fully erase the flash.

For Arduino, follow the instructions given at "Upload tool for LittleFS on ESP8266 (arduino IDE)" at:
https://github.com/earlephilhower/arduino-esp8266littlefs-plugin

<details><summary>Explanation</summary><P/>

LittleFS is a different file system than SPIFFS, and neither one understands the layout used by the other.  Therefore, even if you upload (or already have uploaded) a SPIFFS file system uploaded on the device, your sketch (now using LittleFS) won't recognize it as a valid file system.  The same result would occur if you upload a LittleFS filesystem, if your sketch uses SPIFFS.

If you think back to when you first started using this project, you may recall that you had to upload the SPIFFS file system image once for each board.  Otherwise, there would be nothing in the file system area, and you'd see the same result.

The transition from SPIFFS to LittleFS means that, once again, the file system needs to be written once for each board.  This is true even though you may have previously written it as SPIFFS.

</details><hr/>

<details><summary>Upload image via PlatformIO (VSCode)</summary><P/>

0. Open PlatformIO  (the alien head on far left)
1. Select the environment that you are building for
2. Expand the `Platform` options under that environment
3. Optionally, choose `Build Filesystem Image` to verify building the image works
4. Choose `Upload Filesystem Image` to upload over USB
5. Choose `Upload Filesystem Image OTA` to upload using ArduinoOTA (if your sketch enabled that feature)

<img width="187" alt="image" src="https://user-images.githubusercontent.com/740168/145133296-6d0fe669-3f43-41f2-8c2d-02aedfcb2967.png">

</details><hr/>

**Comment by henrygab** [comment]
FYI ... I've updated the [Wiki](https://github.com/jasoncoon/esp8266-fastled-webserver/wiki) to give additional information on how to update the file system.

I'm going to close this issue, but feel free to re-open if there's something missed.

**Comment by weelmout** [comment]
After uploading with Arduino i can see the IP to use, and after PlatformIO there is nothing except Succes.
