### ISSUE TITLE
Max LED string length?

### ISSUE THREAD

**Issue by sisensee** [jasoncoon/esp8266-fastled-webserver#24]
I have tested this code with small strip sets (90 LEDs) and it works perfectly. I am currently trying to connect it to a 384 LED string that I KNOW works. I have ran it with other code on another NodeMCU however this code suites my needs a little better. 
When hooked up everything "works" i just have a terrible blinking (almost refresh like flashing) that I cant get rid of. Not a grounding issue or anything like that. I was just wondering if anyone has used this with a long set of LEDs?

**Comment by jasoncoon** [comment]
I've only tested up to a string of 300 8mm WS2811 nodes, but I don't see any reason it shouldn't work on much more.

Are you using a level shifter?  I've had very intermittent results without one.  I've had the same strip work fine with one sketch, or with one power supply, but not another.  I have much more consistent results after adding a 74HCT245, large capacitor, and data line resistor.

I assume you're using a three wire LED chipset like WS28xx?  If you're not using IR, you might also try commenting out or removing the IRremoteESP8266 library and all code that uses it, since it uses interrupts.

**Comment by sisensee** [comment]
No level shifter, 1000uf capacitor and a 220ohm resistor for power and signal. Using ws2812b, I am not using the IR although I did leave the library in there, good idea I will pull that out tonight! Thanks for the tip. I even tried to bring the strip length down to a 96 LED. Gonna try with a different NodeMCU as well.

**Comment by jasoncoon** [comment]
Any luck?  Can I close this issue?
