### ISSUE TITLE
firmware modules

### ISSUE THREAD

**Issue by anarchking** [jasoncoon/esp8266-fastled-webserver#29]
Could you tell me what firmware module's your code needs. I'm getting the web app to show but no control and can't get AP mode to work. I've been messing with it for a week now and this is where im stuck. I'm using a nodemcu v.9 with ws2812

**Comment by anarchking** [comment]
Also 5 leds turn on and stay on white, I did change the pin # to 2 which is d4 not sure if that has anything to do with it

**Comment by jasoncoon** [comment]
Sorry, I'm not sure what you mean by "firmware modules".  It uses the Arduino core for ESP8266.  Setup instructions are on the main page and the readme: https://github.com/jasoncoon/esp8266-fastled-webserver

So the sketch compiles and uploads fine?  Any output in the serial monitor?  Tried adding #define FASTLED_ESP8266_NODEMCU_PIN_ORDER at the top of the file?  Tried the simpler FastLED examples?  This app is not the best place to start, since it has so many moving parts, dependencies, etc.

I've never tried a nodemcu module, but there is another open issue here, maybe you could compare notes?  https://github.com/jasoncoon/esp8266-fastled-webserver/issues/27

**Comment by anarchking** [comment]
Yeah I forgot to put the define nodemcu. Works great with router but I'm still working on AP modetrouble shooting.

**Comment by anarchking** [comment]
I appreciate all your hard work and want to thank you. Im trying to make a strip for my friends son, for his wheel chair.

**Comment by jasoncoon** [comment]
Sorry, I haven't used AP mode much.  Have an SSID and password set?  I think the password needs to be at least 8 characters.  Tried the AP mode example in the ESP8266 Arduino repo?  https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino
