### ISSUE TITLE
Other remote

### ISSUE THREAD

**Issue by deennoo** [jasoncoon/esp8266-fastled-webserver#36]
Hello,

Not really an issue here.

First thank you for your sketch who is what i'm looking for since a long long time, i manage to drive 270 led around my desk, that great.

Using your post/get event i manage to use it with my home automation and have a wonderfull remote with Xiaomi Magic Cube.

Now i'm working on the IR control, i manage to use it with a old ir remote i have on my spare parts.

Have you any suggestion for a sketch who allow my to show IR Raw Key Codes ? Can i use hex code from IRrecdemo from esp8266ir lib (the one needed on your sketch ?)

A great evo can be to add a "ir config" page where we can choose action and register a remote key directly

exemple 

On/off (toggle) = click here to learn <--web button
Dimmer + =  click here to learn <--web button
Dimmer - = click here to learn <--web button

etc etc etc, of course that just an idea.

**Comment by jasoncoon** [comment]
Great, glad to hear it's working well for you!

Yeah, the IRrecvDump example should show you the codes for your remote.

Warning though, I've had very mixed results trying to use IR control on the ESP8266 while driving three wire LEDs, such as WS2812, NeoPixel, etc, due to their interrupt requirements.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
