### ISSUE TITLE
Supporting a larger Matrix

### ISSUE THREAD

**Issue by raphaelouzan** [jasoncoon/esp8266-fastled-webserver#45]
What an outstanding project! Congratulations, for putting this together. 

I'm trying to run the code on a 32*8 matrix (with the esp8266). I can change the MatrixHeight, MatrixWidth and NUM_LEDs parameters but it seems that at least the noise based animations use hard coded Coords_X, Coords_Y and Coord_Z arrays. How were these values calculated? What values should I add to extend the matrix by another 8 columns? (from 24->32) 

Thank you so much!

**Comment by jasoncoon** [comment]
Thank you!

Which branch are you using?

Unfortunately, instead of creating new sketches for different builds, I've been creating branches that can't be merged with each other.  I really need to clean up this repository...  :)

There are Map.h files in the [ultim8x8](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/ultim8x8/Map.h), [ultim8x8-cube](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/ultim8x8-cube/Map.h) and [tinytim-cube](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/tinytim-cube/Map.h) branches that are for specific layouts of the [ULTiM8x8](https://www.tindie.com/products/wyolum/ultim8x8-no-solder-rgb-led-panel-system/) and [TinyTiM](https://www.seeedstudio.com/TinyTiM-LED-board-p-2392.html) LED boards and cubes.

Depending on your layout, you may not need a map at all.  For example, with a simple XY matrix made with LED strips, you can usually just use a function that calculates the LED index from XY coordinates, like in the FastLED XYMatrix example: https://github.com/FastLED/FastLED/blob/master/examples/XYMatrix/XYMatrix.ino

**Comment by momo90-2** [comment]
Hi!
Fantastic code! But I have the same problem as raphaelouzan.
Even after studying 
https://github.com/FastLED/FastLED/blob/master/examples/XYMatrix/XYMatrix.ino
I couldnt figure out how to change the code of the master branch for a 12*12 ws2812b matrix.
Could you please help me?

**Comment by Tecky10** [comment]
Hello, really great project is really fun with it. Now I would like to operate a small matrix of 5x7 LEDs with it ... is there an easy way to specify the matrix?

**Comment by jasoncoon** [comment]
Have you tried to incorporate FastLED's XYMatrix example? https://github.com/FastLED/FastLED/blob/master/examples/XYMatrix/XYMatrix.ino

**Comment by jasoncoon** [comment]
OK, I threw together a basic XY matrix example branch: https://github.com/jasoncoon/esp8266-fastled-webserver/tree/xy-matrix
