### ISSUE TITLE
IRremoteESP8266 Arduino library manager

### ISSUE THREAD

**Issue by d0p3x** [jasoncoon/esp8266-fastled-webserver#47]
when i install IRremoteESP8266 via Library Manager the sketch won´t compile. With manual install of IRremoteESP8266 the Sketch compiles.

**Comment by per1234** [comment]
If you look at the link in README.md you can see that this sketch was written using https://github.com/sebastienwarin/IRremoteESP8266. That repository is a fork of https://github.com/markszabo/IRremoteESP8266. It is markszabo/IRremoteESP8266 that you get from the Library Manager installation and development of that library since the time of the fork has made this sketch no longer compatible with markszabo/IRremoteESP8266.

It should be easy enough to update this sketch to work with the latest version of markszabo/IRremoteESP8266 by following this guide:
https://github.com/markszabo/IRremoteESP8266/wiki/Upgrading-to-v2.0

As long as you're not using Platformio, the changes made to the sebastienwarin/IRremoteESP8266 fork are meaningless so it should be possible to still use markszabo/IRremoteESP8266 installed via Library Manager as long as you just select the last release prior to 2.0.0, which is 1.2.0, from the drop down menu in Library Manager. The sketch does compile for me using that version but I don't have the hardware set up to actually test it.
