### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by axsLeaf** [jasoncoon/esp8266-fastled-webserver#61]
Hi, noticed that uploading to SPIFFS is horribly slow, I've added my ESP8266s IP in the app.js, although Chrome fails to load the javascript functions with this message:

`Failed to load http://192.168.1.21/all: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.77' is therefore not allowed access.`

Any tips? I'd like to make some changes to the webpage without waiting 10 minutes for an upload on each edit... Thanks.

**Comment by jasoncoon** [comment]
Sorry, I hope to investigate this and other issues soon.

**Comment by jasoncoon** [comment]
Try increasing the Upload Speed to 921600.  If it fails to upload, retry.  If it always fails, try the next slowest speed.  Depends on which board you're using, and which serial chip it uses.

Also, I had the same issue with SPIFFS uploads taking forever on the Wemos D1 Mini Pro with 16MB flash.  It's because no matter the size of the files you're uploading, it creates a 16MB image.  I resolved this by switching in Arduino Tools menu to Board: Wemos D1 R2 & Mini with Flash Size: 4M (1M SPIFFS)

For the 'Access-Control-Allow-Origin' issue, see this thread: https://github.com/jasoncoon/esp8266-fastled-webserver/issues/86

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
(also appears to be fixed)
