### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by sylvainblot** [jasoncoon/esp8266-fastled-webserver#9]
Hello,

Thanks for your project! I managed to install the filesystem on my HUZZAH. But I can't manage to get to compile the sketch. It's failing because of lib avr doesn't recognise the esp8266.
Can you provide a small installation guide please?

Kind regards

**Comment by jasoncoon** [comment]
I assume you've installed the ESP8266 package for Arduino?  https://github.com/esp8266/Arduino#installing-with-boards-manager  And you've selected the Adafruit Huzzah from the boards menu?  Do other examples compile successfully?  If so, can you enable verbose compilation output in the Arduino preferences, then copy the error output here?

I have provided a very small and quick install guide in the readme: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/README.md

I never spend much time on documentation, since it takes time away from creating other cool new stuff.  :)  If you get it working and want to better document the process, I'd welcome the help.

**Comment by seanspotatobusiness** [comment]
The Wiki and README seem to be identical but I haven't figured out how to edit either. Do I need to fork the project in order to be able to do that? I don't have much to add but may figure out more to add as I go along with my project.

**Comment by paulbram** [comment]
so... I made it as far as getting everything flashed to my ESP8266, but the webserver clearly doesn't have any data files. The "compression" instructions are a bit confusing for me. How am I supposed to get the data files installed into the web server?

**Comment by paulbram** [comment]
ok. so I'll answer my own question. I discovered this: https://github.com/esp8266/arduino-esp8266fs-plugin

Maybe this is obvious for everyone else, but might be helpful to mention it. Thanks!

**Comment by jasoncoon** [comment]
It's already in the readme, installation section: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/README.md#installing
