### ISSUE TITLE
Process flow

### ISSUE THREAD

**Issue by killrmodz** [jasoncoon/esp8266-fastled-webserver#95]
Jason,

Can you give a high level overview on how the js/json/html update the ardiuno code?  I'm trying to duplicate the pages so that it can send different data to different pins so i've been debugging in dreamweaver.  Just trying to track down the power on/off button, I can't seem to make the connection though I know it sends either a 1 or 0 value for power states, I just don't know how the code knows to send it to the appropriate field in the main ino.  Let me know, thanks!!

**Comment by tobi01001** [comment]
Hi, 

have a look here:
https://github.com/jasoncoon/esp8266-fastled-webserver/blob/e2d546bf8cf344226fa5888a392dd653013944ad/esp8266-fastled-webserver.ino#L321

This sets the power states. 'It calls `setPower` where the actual `power `variable will be written and the value will be stored in the EEPROM.

Hope this helps to get you moving....

Don't know how you intend to duplicate things but it may be difficult as you nearly need to duplicate everything as the sketch is imo currently not designed to serve several pins...

regards,
Toby

**Comment by killrmodz** [comment]
![image](https://user-images.githubusercontent.com/44424005/48813929-e1e0e880-ed06-11e8-9883-2a6a19ba1a57.png)

**Comment by killrmodz** [comment]
Jason,

So going between the app.js, the ino, fields.h file, and the index.html... can I use explicit values?  Example: btnOn.click(function() {
    setBooleanFieldValue(field, btnOn, btnOff, 1)
  });

Instead of field, can I just user "power" as that is the field identifier in the fields.h file?  

Also, I've been able to move the animations around to different pins adding these lines in:
#define NUM_LEDS1      2
#define NUM_LEDS2      4

CRGB LEDS1[NUM_LEDS1];
CRGB LEDS2[NUM_LEDS2];

FastLED.addLeds<LED_TYPE, 1 /*datapin*/>(LEDS1, NUM_LEDS21;         // for WS2812 (Neopixel)
FastLED.addLeds<LED_TYPE, 3 /*datapin*/>(LEDS2, NUM_LEDS2);         // for WS2812 (Neopixel)

Then playing with the power:

 if (power == 0) {
    fill_solid(LEDS1, NUM_LEDS1, CRGB::Black); <-- changing LEDS and NUM_LEDS to change pin control
    FastLED.show();
    // FastLED.delay(15);
    return;
  }

I know there will be a lot of duplicating on the INO but if there is a way to be more explicit in the JS, this might be very doable.  The last hurdle is saving all of the settings to eeprom.  There might be where this effort dies.  LOLOL  

Tell me what you all think!!

Thanks!

**Comment by jasoncoon** [comment]
Yeah, app.js is more complicated because it runs on templates and is completely dynamic, depending on the fields returned by the sketch from the `GET /all` request.  You can look at [simple.js](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/data/js/simple.js) for a slightly simpler example.

If you're not concerned with dynamically building the web app, I would recommend just building on simple.js, add a tab for each strip, etc.  You could duplicate each REST request handler in the sketch, making one for each strip, or you could just add a parameter to each that specifies the strip:

https://github.com/jasoncoon/esp8266-fastled-webserver/blob/e2d546bf8cf344226fa5888a392dd653013944ad/esp8266-fastled-webserver.ino#L321

This sounds like a great idea, I wish I had more spare time to help out with it!  I'm looking forward to seeing what you create!

**Comment by killrmodz** [comment]
The current simple... is it supposed to be functioning or just a reference?  The on off do not work...

**Comment by killrmodz** [comment]
So I completely blew up your code... LOL.  I was trying to understand how the /all data was parsed and figure out how to isolate the data being retrieved and returned.  At this point, i'm just trying to individually power on the pin/strips.  Here is what I have in the INO/Field.h/Fields.h... the app.js is hacked up but going to square one because I shouldn't have to hack that up... is what i'm feeling now.  Let me know if i'm even remotely close...

Thanks again Jason.

[killRMODZtest2.zip](https://github.com/jasoncoon/esp8266-fastled-webserver/files/2660896/killRMODZtest2.zip)

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
